---
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: productpage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-productpage
  labels:
    account: productpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      annotations:
        #sidecar.csmopa.io/csmopa-injection: "false"
        sidecar.csmopa.io/opa_image_url: "ccr-2ql0kyd9-pub.cnc.bj.baidubce.com/bms-mesh/opa:latest-istio-bundle"
        sidecar.csmopa.io/rego_source_type: "bundle"
        sidecar.csmopa.io/grpc_policy_path: "istio/authz/allow"
        sidecar.csmopa.io/rego_source_bundle_config: "{\"services\":[{\"name\":\"remote\",\"url\":\"http://bundle-server.nginx:80\"}],\"bundles\":{\"authz\":{\"service\":\"remote\",\"resource\":\"authz.gz\",\"persist\":true,\"polling\":{\"min_delay_seconds\":30,\"max_delay_seconds\":60}}}}"
      labels:
        csmopa-injection: "enabled"
        app: productpage
        version: v1
    spec:
      serviceAccountName: bookinfo-productpage
      containers:
        - name: productpage
          image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          securityContext:
            runAsUser: 1000
      volumes:
        - name: tmp
          emptyDir: {}
---